name: Build and test app in NCS docker container

on:
  pull_request:

jobs:
  build-in-docker:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/nrfconnect/sdk-nrf-toolchain:pr-16290  # steps in this job are executed inside sdk-nrf-toolchain container
      env:
        ACCEPT_JLINK_LICENSE: 1 # set if you want to install JLink
    defaults:
      run:
        shell: bash  # It is required to set `bash` as default shell
    steps:
      - name: Run command in NCS toolchain environment
        run: "west --version"  # This command is executed in bash shell `docker exec <container> bash -c west --version`)
        # It will also install JLink if ACCEPT_JLINK_LICENSE is set to 1
